# Amp editor config, for full config specs visit
# https://github.com/jmacdonald/amp/blob/main/documentation/pages/configuration.md

theme: tango
tab_width: 4
soft_tabs: true
line_wrapping: true

open_mode:
    exclusions: false

search_select:
    max_results: 10
